import type { IrisEvent } from '@/types/event'

const EVENTS_KEY = 'iris-events'
const COUNTER_KEY = 'iris-event-counter'

const sampleEvents: IrisEvent[] = [
  {
    id: 'IC-001',
    createdAt: '2026-02-18T09:15:00.000Z',
    status: 'documented',
    description: {
      whoAffected: ['All customers', 'Business customers'],
      whoAffectedCustom: '',
      userImpact: 'blocked',
      userScope: 'widespread',
      workaroundAvailable: 'no',
      actionRequired: 'mandatory',
      actionDescription: 'Users must wait for resolution. No workaround available.',
      timing: 'now',
      leadTime: '',
      securityCompliance: false,
      whatHappened: 'Complete outage of the MagentaCLOUD storage service. Users cannot access, upload, or download files. Sync clients show connection errors.',
      additionalNotes: 'Root cause identified as database cluster failure. Engineering team is working on recovery.',
    },
    classification: {
      type: 'Notification',
      severity: 'Critical',
      severityExplanation: 'Service fully unavailable, widespread user impact, no workaround available.',
      channels: ['E-Mail', 'Banner', 'Dashboard', 'Status Page'],
      purpose: 'Inform users about ongoing outage and expected resolution.',
      trigger: 'immediate',
      escalation: true,
      typePath: [
        { nodeId: 'q1', questionText: 'What type of information?', selectedLabel: 'Service disruption' },
        { nodeId: 'q2', questionText: 'Is the service affected?', selectedLabel: 'Yes, fully unavailable' },
      ],
      severityOverride: null,
    },
    typeContext: null,
    generatedText: null,
  },
  {
    id: 'IC-002',
    createdAt: '2026-02-19T14:30:00.000Z',
    status: 'documented',
    description: {
      whoAffected: ['All customers'],
      whoAffectedCustom: '',
      userImpact: 'degraded',
      userScope: 'widespread',
      workaroundAvailable: 'yes_documented',
      actionRequired: 'recommended',
      actionDescription: 'Users can switch to the legacy webmail interface as a temporary alternative.',
      timing: 'now',
      leadTime: '',
      securityCompliance: false,
      whatHappened: 'Intermittent slowness in the E-Mail Center. Sending and receiving emails may be delayed by up to 15 minutes. Webmail interface loads slowly.',
      additionalNotes: 'Performance degradation traced to increased load on mail relay servers.',
    },
    classification: {
      type: 'Notification',
      severity: 'High',
      severityExplanation: 'Core service degraded, widespread user impact, documented workaround exists.',
      channels: ['E-Mail', 'Banner', 'Dashboard'],
      purpose: 'Notify users of degraded email performance and available workaround.',
      trigger: 'immediate',
      escalation: false,
      typePath: [
        { nodeId: 'q1', questionText: 'What type of information?', selectedLabel: 'Service disruption' },
        { nodeId: 'q2', questionText: 'Is the service affected?', selectedLabel: 'Yes, partially degraded' },
      ],
      severityOverride: null,
    },
    typeContext: null,
    generatedText: null,
  },
  {
    id: 'IC-003',
    createdAt: '2026-02-20T08:00:00.000Z',
    status: 'documented',
    description: {
      whoAffected: ['All customers'],
      whoAffectedCustom: '',
      userImpact: 'no_impact',
      userScope: 'widespread',
      workaroundAvailable: 'yes_documented',
      actionRequired: 'recommended',
      actionDescription: 'Users should save their work before the maintenance window begins.',
      timing: 'scheduled',
      leadTime: 'more_than_7_days',
      securityCompliance: false,
      whatHappened: 'Scheduled maintenance for the Telefoniecenter platform on March 8, 2026, from 02:00 to 06:00 CET. VoIP and call management features will be temporarily unavailable.',
      additionalNotes: 'Quarterly infrastructure upgrade. Emergency calls (110, 112) are not affected.',
    },
    classification: {
      type: 'Notification',
      severity: 'Medium',
      severityExplanation: 'Scheduled downtime, advance notice given, limited time window.',
      channels: ['E-Mail', 'Banner'],
      purpose: 'Inform users in advance about planned maintenance window.',
      trigger: 'scheduled',
      escalation: false,
      typePath: [
        { nodeId: 'q1', questionText: 'What type of information?', selectedLabel: 'Planned maintenance' },
      ],
      severityOverride: null,
    },
    typeContext: null,
    generatedText: null,
  },
  {
    id: 'IC-004',
    createdAt: '2026-02-21T11:45:00.000Z',
    status: 'documented',
    description: {
      whoAffected: ['All customers'],
      whoAffectedCustom: '',
      userImpact: 'no_impact',
      userScope: 'widespread',
      workaroundAvailable: 'yes_documented',
      actionRequired: 'no',
      actionDescription: '',
      timing: 'scheduled',
      leadTime: '1_to_7_days',
      securityCompliance: false,
      whatHappened: 'New two-factor authentication option available for MagentaCLOUD. Users can now enable TOTP-based 2FA in their security settings for enhanced account protection.',
      additionalNotes: 'Feature rollout completed for all users. SMS-based 2FA remains available as an alternative.',
    },
    classification: {
      type: 'Notification',
      severity: 'Low',
      severityExplanation: 'Informational update, no service impact, no user action required.',
      channels: ['E-Mail', 'Dashboard'],
      purpose: 'Inform users about a new security feature they can optionally enable.',
      trigger: 'scheduled',
      escalation: false,
      typePath: [
        { nodeId: 'q1', questionText: 'What type of information?', selectedLabel: 'New feature announcement' },
      ],
      severityOverride: null,
    },
    typeContext: null,
    generatedText: null,
  },
  {
    id: 'IC-005',
    createdAt: '2026-02-22T16:20:00.000Z',
    status: 'documented',
    description: {
      whoAffected: ['Business customers'],
      whoAffectedCustom: '',
      userImpact: 'blocked',
      userScope: 'limited',
      workaroundAvailable: 'yes_complex',
      actionRequired: 'mandatory',
      actionDescription: 'Affected users must re-authenticate via the business portal to restore access.',
      timing: 'now',
      leadTime: '',
      securityCompliance: true,
      whatHappened: 'SSL certificate renewal issue causing authentication failures for Microsoft 365 Business integration. Affected users see "certificate expired" errors when accessing synced mailboxes.',
      additionalNotes: 'Certificate vendor notified. New certificate expected within 2 hours. Security team monitoring for unauthorized access attempts.',
    },
    classification: {
      type: 'Notification',
      severity: 'High',
      severityExplanation: 'Authentication blocked for subset of business users, security-relevant, complex workaround.',
      channels: ['E-Mail', 'Banner', 'Dashboard', 'Status Page'],
      purpose: 'Alert affected business users about authentication issue and required action.',
      trigger: 'immediate',
      escalation: true,
      typePath: [
        { nodeId: 'q1', questionText: 'What type of information?', selectedLabel: 'Service disruption' },
        { nodeId: 'q2', questionText: 'Is the service affected?', selectedLabel: 'Yes, fully unavailable' },
      ],
      severityOverride: null,
    },
    typeContext: null,
    generatedText: null,
  },
  {
    id: 'IC-006',
    createdAt: '2026-02-23T07:00:00.000Z',
    status: 'documented',
    description: {
      whoAffected: ['All customers'],
      whoAffectedCustom: '',
      userImpact: 'degraded',
      userScope: 'limited',
      workaroundAvailable: 'yes_documented',
      actionRequired: 'no',
      actionDescription: '',
      timing: 'now',
      leadTime: '',
      securityCompliance: false,
      whatHappened: 'SpeedOn option activation delayed for new bookings. Users who recently booked SpeedOn may not see the speed upgrade for up to 2 hours instead of the usual 10 minutes.',
      additionalNotes: 'Provisioning queue backlog being cleared. Existing SpeedOn activations are not affected.',
    },
    classification: {
      type: 'Notification',
      severity: 'Medium',
      severityExplanation: 'Non-critical degradation, limited user impact, self-resolving.',
      channels: ['Banner', 'Dashboard'],
      purpose: 'Inform users about temporary delay in SpeedOn activation.',
      trigger: 'immediate',
      escalation: false,
      typePath: [
        { nodeId: 'q1', questionText: 'What type of information?', selectedLabel: 'Service disruption' },
        { nodeId: 'q2', questionText: 'Is the service affected?', selectedLabel: 'Yes, partially degraded' },
      ],
      severityOverride: null,
    },
    typeContext: null,
    generatedText: null,
  },
]

export function seedEventsIfEmpty(): void {
  const existing = localStorage.getItem(EVENTS_KEY)
  if (existing) return

  localStorage.setItem(EVENTS_KEY, JSON.stringify(sampleEvents))
  localStorage.setItem(COUNTER_KEY, String(sampleEvents.length))
}
